---
# Playbook: add_ztp_host.yml
# Description: Adds a host to a specified AWX/Tower inventory.
#              Designed to be triggered by a ZTP process, receiving the
#              new switch's IP address via extra_vars.

- name: Add ZTP Discovered Host to AWX Inventory
  hosts: localhost # Run this playbook on the AWX control node itself
  gather_facts: false # Keep this false for efficiency on localhost
  connection: local

  # 'switch_ip_address' is expected to be provided via extra_vars when launching the job template.
  # 'ztp_inventory_name' is the exact name of your ZTP inventory in AWX.
  vars:
    ztp_inventory_name: "ZTP Inventory"

  tasks:
    - name: Add the new switch IP to the ZTP inventory
      awx.awx.host: # Or ansible.tower.host depending on your collection/version
        name: "192.168.100.50"
        description: "Auto-discovered via ZTP on {{ now(utc=True, fmt='%Y-%m-%dT%H:%M:%SZ') }}"
        inventory: "ZTP Inventory"
        state: present
        enabled: true

        # --- AWX API Connection Parameters ---
        controller_host: "{{ api_url }}"
        controller_oauthtoken: "{{ api_token }}"
        validate_certs: "false"
      register: add_host_result
      delegate_to: localhost

    - name: Display result of host addition
      ansible.builtin.debug:
        var: add_host_result
