---
- name: Add ZTP Discovered Host to AWX Inventory
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Add the new switch IP to the ZTP inventory
      awx.awx.host:
        name: "192.168.100.50"
        description: "Auto-discovered via ZTP on {{ now(utc=True, fmt='%Y-%m-%dT%H:%M:%SZ') }}"
        inventory: "ZTP Inventory"
        state: present
        enabled: true
        controller_host: "{{ lookup('env', 'AWX_API_URL') }}"
        controller_oauthtoken: "{{ lookup('env', 'AWX_OAUTH_TOKEN') }}"
        validate_certs: "false"
      register: add_host_result
      delegate_to: localhost

    - name: Display result of host addition
      ansible.builtin.debug:
        var: add_host_result
