- name: Add ZTP Discovered Host to AWX Inventory
  hosts: localhost # Run this playbook on the AWX control node itself
  gather_facts: false
  connection: local

  vars:
    switch_ip: "192.168.100.50"
    ztp_inventory_name: "ZTP Inventory"

  tasks:
    - name: Fail if switch_ip is not provided
      ansible.builtin.fail:
        msg: "Mandatory variable 'switch_ip_address' was not provided in extra_vars."
      when: switch_ip is omitted or switch_ip == ""

    - name: Ensure ztp_inventory_name is set
      ansible.builtin.fail:
        msg: "Variable 'ztp_inventory_name' is not set or is empty. Please edit the playbook vars section."
      when: ztp_inventory_name is not defined or ztp_inventory_name == ""

    - name: Add the new switch IP to the ZTP inventory
      awx.awx.host:
        name: "{{ switch_ip }}"
        description: "Auto-discovered via ZTP on {{ ansible_date_time.iso8601 }}"
        inventory: "{{ ztp_inventory_name }}"
        state: present
      register: add_host_result
      delegate_to: localhost

    - name: Display result of host addition
      ansible.builtin.debug:
        var: add_host_result
