---
# This task ensures the variables are pulled in from the main playbook.
- name: Gather facts explicitly
  ansible.builtin.setup:
  
- name: Display some facts
  ansible.builtin.debug:
    msg:
      - "Hostname: {{ ansible_net_hostname }}"
      - "Version: {{ ansible_net_version }}"
      - "Model: {{ ansible_net_model }}"
      - "Serial: {{ ansible_net_serialnum }}"

      - "ZTP Hostname: {{ ztp_hostname }}"
      - "ZTP IP Address: {{ ztp_ip_address }}"
