---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream10

dependencies:
  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  python: requirements.txt
  galaxy: requirements.yml
  system: bindep.txt

additional_build_steps:
  prepend_final: |
    RUN update-crypto-policies --set LEGACY
    RUN echo "System crypto policy set to LEGACY." && \
        update-crypto-policies --show | grep -q LEGACY || exit 1
